---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
        - name: Check installation
          stat:
                  path: /opt/splunk
          register: splunk_install

        - name: Gets tarball
          get_url:
            url="https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=7.2.3&product=splunk&filename=splunk-7.2.3-06d57c595b80-linux-2.6-amd64.deb&wget=true"
            dest="/home/bhanuchandra_sabbavarapu"
          when: splunk_install.stat.exists == False

        - name: install splunk
          command: dpkg -i /home/bhanuchandra_sabbavarapu/splunk-7.2.3-06d57c595b80-linux-2.6-amd64.deb
          register: installed_splunk
          when: splunk_install.stat.exists == False

        - name: splunk start by accepting license
          command: /opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt 
          when: installed_splunk.changed

        - name: splunk user-seed
          copy:
            dest: "/opt/splunk/etc/system/local/user-seed.conf"
            content: |
                 [user_info]
                 USERNAME = bhanu
                 PASSWORD = Tcs@1234
          when: installed_splunk.changed

        - name: splunk restart after user seed
          command: /opt/splunk/bin/splunk restart
          when: installed_splunk.changed

        - name: enable splunk boot start
          command: /opt/splunk/bin/splunk enable boot-start
          when: installed_splunk.changed
