---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
        - name: Gets tarball
          get_url:
            url="https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=7.2.3&product=splunk&filename=splunk-7.2.3-06d57c595b80-linux-2.6-amd64.deb&wget=true"
            dest="/home/bhanuchandra_sabbavarapu"
